import argparse

import os

from oracle_module.answerer import oracle


def main(args):
    # get ood result
    ood_result = get_ood_result(args)

    # get augmented question generated by DramaQG model
    aug_question = get_aug_question(args, ood_result)

    # get answer for aug question
    aug_answer = oracle(aug_question)


    # get original DramaQA model
    dramaqa_model = model(args)


    # train for DramaQA
    pass

    # inference for DramaQA
    pass


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Argparse Tutorial')
    # argument는 필요한 만큼 추가한다.
    parser.add_argument('--data-path', type=str, help='path to DramaQA dataset')

    args = parser.parse_args()
    main(args)
